"""Monitoring FIT extraction and sleep-aware feature foundations."""

from .foundation import (
    FIT_EPOCH_S,
    HEART_RATE_COLUMNS,
    STRESS_COLUMNS,
    SEMANTIC_WINDOW_COLUMNS,
    build_monitoring_daily_features,
    build_monitoring_foundation_summary_markdown,
    build_semantic_sleep_windows,
    classify_heart_rate_value,
    classify_stress_value,
    derive_local_utc_offsets,
    extract_monitoring_messages,
    materialize_monitoring_fit,
    normalize_heart_rate_frame,
    normalize_stress_frame,
    resolve_timestamp_16,
)
from .core import (
    MonitoringCoreConfig,
    build_monitoring_analysis_windows,
    build_monitoring_core_features,
    build_monitoring_core_features_summary_markdown,
    build_monitoring_features_full,
    build_monitoring_features_full_summary_markdown,
    build_monitoring_quality_index,
    build_monitoring_quality_summary_markdown,
    build_monitoring_quality_windows,
    select_monitoring_core_features,
)
from .features import (
    MonitoringFeaturesFullConfig,
    build_monitoring_feature_catalog,
    build_monitoring_feature_catalog_markdown,
)

__all__ = [
    "HEART_RATE_COLUMNS",
    "FIT_EPOCH_S",
    "MonitoringCoreConfig",
    "MonitoringFeaturesFullConfig",
    "STRESS_COLUMNS",
    "SEMANTIC_WINDOW_COLUMNS",
    "build_monitoring_analysis_windows",
    "build_monitoring_core_features",
    "build_monitoring_core_features_summary_markdown",
    "build_monitoring_feature_catalog",
    "build_monitoring_feature_catalog_markdown",
    "build_monitoring_features_full",
    "build_monitoring_features_full_summary_markdown",
    "build_monitoring_daily_features",
    "build_monitoring_foundation_summary_markdown",
    "build_monitoring_quality_index",
    "build_monitoring_quality_summary_markdown",
    "build_monitoring_quality_windows",
    "build_semantic_sleep_windows",
    "classify_heart_rate_value",
    "classify_stress_value",
    "derive_local_utc_offsets",
    "extract_monitoring_messages",
    "materialize_monitoring_fit",
    "normalize_heart_rate_frame",
    "normalize_stress_frame",
    "resolve_timestamp_16",
    "select_monitoring_core_features",
]
